### ISSUE TITLE
Sobre possível nova palestra

### ISSUE THREAD

**Issue by tofanelli** [nic/reactconf.com.br#3]
Opa...

tranquilo?

Mandei um email sobre uma possível nova palestra. Não sei se viram ou se viram ou não ficaram interessados. Quando puder, veja se é interessante o conteúdo.

Valeu =)

**Comment by nic** [comment]
Opa mano, o C4P já está encerrado! De qualquer forma muito obrigado por ter enviado, não deixa de fazer este talk em alguém meetup pra galera!

- https://www.meetup.com/ReactJS-SP/
- https://www.facebook.com/reactssa/
- https://www.meetup.com/reactbh/
- https://www.meetup.com/pt-BR/ReactJS-CWB/
- https://www.meetup.com/pt-BR/React-Maringa/
- https://www.meetup.com/pt-BR/React-Rio-de-Janeiro/
- https://www.meetup.com/React-Porto-Alegre/
- https://www.meetup.com/ReactJS-Floripa/
- https://www.meetup.com/React-Joinville/
- https://www.meetup.com/pt-BR/React-Goiania/

**Comment by tofanelli** [comment]
Boa então!!


Valeu =)
